name: update dependencies

on:
  workflow_dispatch:   # 手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false # 不自动安装依赖，后续步骤手动执行

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install npm-check-updates
        run: pnpm add -g npm-check-updates

      - name: Check and update dependencies
        run: |
          ncu -u  # 更新 package.json 中的版本范围
          pnpm install --no-frozen-lockfile  # 更新 pnpm-lock.yaml 并安装依赖

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): update dependencies to latest'
          body: |
            This PR updates project dependencies to their latest versions using `pnpm`.

            - Auto-generated by [GitHub Actions](https://github.com/features/actions)
          branch: 'deps/auto-update'
          base: 'main'
          delete-branch: true
